import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";
import axios from "axios";
import { UserProvider } from "./context/UserContext";
import { MarketProvider } from "./context/MarketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.withCredentials = true; // send the HttpOnly cookie
axios.defaults.baseURL = process.env.NEXT_PUBLIC_BASE_URL;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <MarketProvider>
          <Appbar/>
          {children}
          </MarketProvider>
        </UserProvider>
      </body>
    </html>
  );
}
