[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1.12"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = {version ="1.47.1",  features = ["rt-multi-thread", "macros"]}
uuid = { version = "1.x", features = ["v4"] }